### ISSUE TITLE
Lemma should depend on Aspect

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_Russian-SynTagRus#11]
I was just looking at the SynTagRus data and it seems that the lemma of дать is давать and the same for other Impf/Perf pairs.

It was marked for fixing in v2, but seems to have been missed, so I'll add an issue here pointing to it: https://github.com/UniversalDependencies/docs/issues/341.

**Comment by olesar** [comment]
rescheduled v.2.2:
Perfective verbs that are now tagged with imperfective lemmas should be fixed
@olesar has a list of lemmas for perfectives

**Comment by Kira-D** [comment]
Fixed in v2.2
