### ISSUE TITLE
Part of speech of кто-то

### ISSUE THREAD

**Issue by ftyers** [UniversalDependencies/UD_Russian-SynTagRus#12]
Should кто-то be tagged as a NOUN ? кто is tagged as PRON.

**Comment by dan-zeman** [comment]
I do not know how it is tagged in the current data but I believe that _кто-то_ is an indefinite pronoun.

**Comment by Kira-D** [comment]
@ftyers  I think you were looking at the release 1.4, which has additional manual corrections provided by @olesar.
Now, in 2.0 it is tagged as NOUN, but I agree with @dan-zeman and I'll make them pronouns

**Comment by Kira-D** [comment]
fixed in 2.1
