### ISSUE TITLE
deprel '_'

### ISSUE THREAD

**Issue by olesar** [UniversalDependencies/UD_Russian-SynTagRus#17]
The stats shows 1445 cases of "_" relation in UD-Russian-SynTagRus. Are they still there?

**Comment by dan-zeman** [comment]
Good catch! It is actually not an error in the data (otherwise the treebank would not pass validation). It is an error in the script that collects the statistics. It mistakenly included the empty nodes.

It is fixed now and statistics in all affected treebanks are updated.
