### ISSUE TITLE
format error

### ISSUE THREAD

**Issue by fostroll** [UniversalDependencies/UD_Russian-SynTagRus#29]
Последний токен файла train-c.conllu содержит в поле MISC токен "_~" (вместо "_"). Этот токен нестандартный, приходится софт для чтения CoNLL-U править специально под него.

**Comment by dan-zeman** [comment]
Thanks for reporting this. The file is not formally invalid, as the CoNLL-U format allows this. However, it was obviously unintended here. Fixed now in the `dev` branch, the fix will be propagated to release 2.10 in May.
