### ISSUE TITLE
Coordination misannotation in 2011Petrushka.xml_59

### ISSUE THREAD

**Issue by nikitakit** [UniversalDependencies/UD_Russian-SynTagRus#31]
The sentence `2011Petrushka.xml_59` was flagged by my scripts as having a degree of non-projectivity that is otherwise unattested in the Russian treebanks, but this appears to just be an annotation artifact/error.

> Как было записано в академическом Уставе 1747 года, "всяк академик иметь должен<sub>14</sub> при себе адъюнкта, который должность имеет<sub>21</sub> помощника академику, а притом стараться должен<sub>28</sub> как академик<sub>30</sub> об адъюнкте, так и адъюнкт<sub>36</sub> сам о себе, чтобы ему со временем заступить академика своего, по отбытии его, место".

```
14      должен  должен  ADJ     _       Degree=Pos|Gender=Masc|Number=Sing|Variant=Short        3       nsubj:pass      3:nsubj:pass    _
21      имеет   иметь   VERB    _       Aspect=Imp|Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin|Voice=Act      17      acl:relcl       17:acl:relcl    _
28      должен  должен  ADJ     _       Degree=Pos|Gender=Masc|Number=Sing|Variant=Short        21      conj    17:acl:relcl|21:conj    _
30      академик        академик        NOUN    _       Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing   28      nsubj   27:nsubj|28:nsubj       _
36      адъюнкт адъюнкт NOUN    _       Animacy=Anim|Case=Nom|Gender=Masc|Number=Sing   21      conj    36.1:nsubj      _
```

адъюнкт<sub>36</sub> should probably attach to должен<sub>28</sub> (or possibly академик<sub>30</sub>), but certainly not имеет<sub>21</sub>.

**Comment by dan-zeman** [comment]
Thanks for reporting! Fixed in dev.
